import org.json.JSONObject;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class MyClassTest {

    @Test
    public void testCountJsonObjWithCount2() {
        MyClass myClass = new MyClass();

        try {
            JSONObject result = myClass.countJsonObj(2, "CountName", "ID");

            Assertions.assertEquals("ExpectedCountNum", result.getString("alert"));
            Assertions.assertEquals("CountName", result.getString("alertname"));
            Assertions.assertEquals("ID", result.getString("id"));

        } catch (Exception e) {
            Assertions.fail("Unexpected exception occurred: " + e.getMessage());
        }
    }

    @Test
    public void testCountJsonObjWithCount4() {
        MyClass myClass = new MyClass();

        try {
            JSONObject result = myClass.countJsonObj(4, "CountName", "ID");

            Assertions.assertEquals("ExpectedCountNum", result.getString("alert"));
            Assertions.assertEquals("CountName", result.getString("alertname"));
            Assertions.assertEquals("ID", result.getString("id"));

        } catch (Exception e) {
            Assertions.fail("Unexpected exception occurred: " + e.getMessage());
        }
    }

    @Test
    public void testCountJsonObjWithCount8() {
        MyClass myClass = new MyClass();

        try {
            JSONObject result = myClass.countJsonObj(8, "CountName", "ID");

            Assertions.assertEquals("ExpectedCountNum", result.getString("alert"));
            Assertions.assertEquals("CountName", result.getString("alertname"));
            Assertions.assertEquals("ID", result.getString("id"));

        } catch (Exception e) {
            Assertions.fail("Unexpected exception occurred: " + e.getMessage());
        }
    }

    @Test
    public void testCountJsonObjWithInvalidCount() {
        MyClass myClass = new MyClass();

        try {
            JSONObject result = myClass.countJsonObj(5, "CountName", "ID");

            Assertions.fail("Exception was expected but not thrown.");

        } catch (Exception e) {
            Assertions.assertEquals("Count request type cannot be what was input: 5", e.getMessage());
        }
    }
}

